baseurl: "/radblog/"
url: "https://quadient.github.io/radblog/"
domain: "quadient.github.io"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-multiple-languages-plugin

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed

languages: ["en", "cz"]
exclude_from_localizations: ["javascript", "images", "css"]
